# Generated by Django 3.1.6 on 2021-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_info', models.PositiveSmallIntegerField(blank=True, verbose_name='количество квартир')),
                ('total_area', models.PositiveSmallIntegerField(blank=True, verbose_name='общая площадь')),
                ('living_space', models.PositiveSmallIntegerField(blank=True, verbose_name='жилая площадь')),
                ('kitchen_space', models.PositiveSmallIntegerField(blank=True, verbose_name='площадь кухни')),
                ('floor', models.PositiveSmallIntegerField(blank=True, verbose_name='этаж')),
                ('is_balcony', models.CharField(blank=True, max_length=255, verbose_name='наличие балкона')),
                ('house_type', models.CharField(blank=True, max_length=255, verbose_name='тип дома (материал)')),
                ('house_name', models.CharField(blank=True, max_length=255, verbose_name='название ЖК')),
                ('finishing', models.CharField(blank=True, max_length=255, verbose_name='отделка')),
                ('is_parking', models.CharField(blank=True, max_length=255, verbose_name='Наличие парковки')),
                ('is_cctv', models.CharField(blank=True, max_length=255, verbose_name='наличие видеонаблюдения')),
                ('is_concierge', models.CharField(blank=True, max_length=255, verbose_name='наличие консьержа')),
                ('fenced_area', models.CharField(blank=True, max_length=255, verbose_name='огороженная территория')),
                ('distance_nearest_metro', models.CharField(blank=True, max_length=255, verbose_name='Расстояние до ближайшей станции')),
                ('apartment_link', models.CharField(default=0, max_length=255, verbose_name='Ссылка на объявление квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_config', models.JSONField(verbose_name='Конфиг с разметкой для параметров апартаментов')),
                ('apartments_page_config', models.JSONField(verbose_name='Конфиг для главной страницы с настройкой параметров')),
                ('apartment_page_sections_config', models.JSONField(verbose_name='Конфиг для страницы с квартирами')),
                ('apartment_page_config', models.JSONField(verbose_name='Конфиг для страницы с квартирой')),
                ('status', models.PositiveSmallIntegerField(verbose_name='статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
