# Generated by Django 3.1.4 on 2021-01-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_info', models.PositiveSmallIntegerField(verbose_name='количество квартир')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='общая площадь')),
                ('living_space', models.PositiveSmallIntegerField(verbose_name='жилая площадь')),
                ('kitchen_space', models.PositiveSmallIntegerField(verbose_name='площадь кухни')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='этаж')),
                ('is_balcony', models.BooleanField(verbose_name='наличие балкона')),
                ('house_type', models.CharField(max_length=50, null=True, verbose_name='тип дома (материал)')),
                ('finishing', models.CharField(max_length=50, null=True, verbose_name='отделка')),
                ('is_parking', models.CharField(max_length=50, null=True, verbose_name='Наличие парковки')),
                ('is_cctv', models.BooleanField(null=True, verbose_name='наличие видеонаблюдения')),
                ('is_concierge', models.CharField(max_length=50, null=True, verbose_name='наличие консьержа')),
                ('fenced_area', models.BooleanField(null=True, verbose_name='огороженная территория')),
                ('distance_nearest_metro', models.CharField(default='Не определено', max_length=25, verbose_name='Расстояние до ближайшей станции')),
                ('distance_nearest_ground_transport', models.CharField(max_length=25, verbose_name='Расстояние до ближайшей остановки наземного транспорта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('apartment_params_config', models.JSONField(verbose_name='Конфиг с разметкой для параметров апартаментов')),
                ('main_page_config', models.JSONField(verbose_name='Конфиг для главной страницы с настройкой параметров')),
                ('apartments_page_config', models.JSONField(verbose_name='Конфиг для страницы с квартирами')),
                ('apartment_page_config', models.JSONField(verbose_name='Конфиг для страницы с квартирой')),
                ('status', models.PositiveSmallIntegerField(verbose_name='статус')),
            ],
        ),
    ]
