# Generated by Django 3.1.6 on 2021-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='apartment_link',
            field=models.CharField(default=0, max_length=255, verbose_name='Ссылка на объявление квартиры'),
            preserve_default=False,
        ),
    ]
