# Generated by Django 3.1.6 on 2021-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210213_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='fenced_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='огороженная территория'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='finishing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='отделка'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='house_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название ЖК'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='house_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='тип дома (материал)'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='is_balcony',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='наличие балкона'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='is_cctv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='наличие видеонаблюдения'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='is_concierge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='наличие консьержа'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='is_parking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наличие парковки'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='kitchen_space',
            field=models.FloatField(blank=True, null=True, verbose_name='площадь кухни'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='living_space',
            field=models.FloatField(blank=True, null=True, verbose_name='жилая площадь'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='rooms_info',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество квартир'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name='общая площадь'),
        ),
    ]
