# Generated by Django 3.1.6 on 2021-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210213_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='kitchen_space',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='площадь кухни'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='living_space',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='жилая площадь'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='total_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='общая площадь'),
        ),
    ]
