# Generated by Django 3.1.6 on 2021-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210213_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentinfo',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='цена'),
        ),
    ]
